### ISSUE TITLE
Development of unit tests for the user controller 

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard-api#121]
The goal is to develop a new suite of unit tests to check the following controller: 
`cboard-api\api\controllers\user.js`
Use the following test suite as an example of what we have to do: 
`cboard-api\test\controllers\board.js`

Check the Readme file to understand how to run the unit tests.
Here you have a tutorial on how to develop nodejs and express unit tests: https://medium.com/@ehtemam/writing-test-with-supertest-and-mocha-for-expressjs-routes-555d2910d2c2

**Comment by tomivm** [comment]
In process. what you prefer to use for assertions? assert from node.js or chai like in the board test?

**Comment by martinbedouret** [comment]
you have to use the same pattern as the existing board test suite
