### ISSUE TITLE
Logger for cboard-api

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard-api#13]
I don't have enough knowledge in order to provide details here. Open to suggestions for everyone that wants to collaborate.

**Comment by BrendanFDMoore** [comment]
Are you looking to hook with up to a logging service, or simply collect log files on the host for now?

In either case, a solution like [winston](https://www.npmjs.com/package/winston) is a good and straightforward starting point. It would allow us to configure desired log levels for dev and prod, along with storage limitations etc. These files would then serve as the basis for any remote log aggregation (datadog, sumologic, etc).

**Comment by BrendanFDMoore** [comment]
I can take a pass at adding this @martinbedouret 👌

**Comment by martinbedouret** [comment]
Awesome @BrendanFDMoore , please take  it.

**Comment by sylvansson** [comment]
See https://github.com/cboard-org/cboard-api/pull/98.
