### ISSUE TITLE
Its necessary to put a barrer to impide upload files that are not images with /media endpoint?

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard-api#146]
I did some tries to upload pdf and videos with /media and I get a status 200; @sylvansson

**Comment by sylvansson** [comment]
That would be a question for @martinbedouret. But based on the frontend code, we also use this endpoint to upload audio files, so we shouldn't only allow images.

**Comment by tomivm** [comment]
good point. I did not consider that.
