### ISSUE TITLE
Session secret hard-coded into app.js?

### ISSUE THREAD

**Issue by toolness** [cboard-org/cboard-api#46]
Hi!  I was just looking through`app.js` and noticed the following in it, around line 29:

```js
  //use sessions for tracking logins
  app.use(
    session({
      secret: 'work hard',
      resave: true,
      saveUninitialized: false,
      store: new MongoStore({
        mongooseConnection: db
      })
    })
  );
```

The session secret is hard-coded to `'work hard'`... I'm not sure what the full scope of your user sessions is, but I'm curious if this could lead to any kind of security vulnerabilities.  Either way, it might be useful to either change (e.g. by pulling the secret from an environment variable) or document in a comment!

**Comment by martinbedouret** [comment]
this is useful https://expressjs.com/en/advanced/best-practice-security.html
