### ISSUE TITLE
Update README file in order to include Postman collection explanation and write some examples of calls.

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard-api#8]
We need to improve the README file in order to give details on how to run and check API.
Need to include POSTman file and write some examples of calls.
Location of Postman collection is:

- cboard-api\test\postman\cboard-api.postman_collection.json

**Comment by amberleyromo** [comment]
Did you open this to work on it? If not, I can do it -- it's been on my list to familiarize with the api repo anyway.

**Comment by martinbedouret** [comment]
you can take it, please

**Comment by sylvansson** [comment]
What is the use case for these Postman request descriptions?  If we don't _need_ to use Postman, then I think we could simply update `swagger.yaml` to be more descriptive and include examples, and serve the documentation with something like [swagger-ui-express](https://github.com/scottie1984/swagger-ui-express) or [ReDoc](https://github.com/Redocly/redoc) (which is self-hosted).

**Comment by martinbedouret** [comment]
@sylvansson I have opened this ticket to assign it to a new developer who joins the team in order to get familiar with the API. 
Nevertheless I liked your idea of make some improvement in swagger. Could you please open a new issue and provide some information about what are your thoughts and suggestions for swagger and ui-express?

**Comment by martinbedouret** [comment]
Done
